spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  application:
    name: LpTasks
  datasource:
    url: jdbc:postgresql://localhost:5432/LpTasks
    password: mistery123
    username: lukas
server:
  port: 8080
