spring:
  security:
    token:
      secret: "encrypted123"
    user:
      name: lukas
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
  cache:
    type: redis
  application:
    name: LpTasks
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/LpTasks
    password: mistery123
    username: lukas
server:
  port: 8080
